export default {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  UPDATE_TODO: "UPDATE_TODO",

  SET_INPUT_TITLE: "SET_INPUT_TITLE",
  SET_INPUT_CONTENT: "SET_INPUT_CONTENT",
  SET_INPUT_ID: "SET_INPUT_ID",
  RESET_INPUT: "RESET_INPUT",
};

